#!/usr/bin/env node
"use strict";

const { spawnSync } = require("child_process");
const { getBinaryPath } = require("../index.js");

let bin;
try {
  bin = getBinaryPath();
} catch (e) {
  console.error(e.message);
  process.exit(1);
}

const result = spawnSync(bin, process.argv.slice(2), { stdio: "inherit" });
if (result.error) {
  console.error(result.error.message);
  process.exit(1);
}
process.exit(result.status ?? 0);
